esphome:
  name: "plantmonitor-1"
  friendly_name: plantmonitor-1
  platformio_options:
    board_build.f_cpu: 160000000L

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: #KEY

ota:
  password: #PWD

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
    port: 80

light:
  - platform: binary
    name: "Blue Light"
    output: light_output
    id: led_light
    restore_mode: ALWAYS_OFF

output:
  - platform: gpio
    pin: GPIO2
    id: light_output
    inverted: true

sensor:
  - platform: adc
    pin: A0
    id: "adcRaw_Moisture"
    accuracy_decimals: 5
    name: "Plant - Raw Moisture"
    update_interval: 30s

  - platform: template
    id: "moisture_sensor"
    name: "Plant - Moisture Level"
    lambda: |-
      return (id(adcRaw_Moisture).state - 0.62) / (0.29 - 0.62) * 100.0;
    unit_of_measurement: '%'
    update_interval: 30s

  - platform: wifi_signal
    name: "Plant - WiFi Signal Sensor"
    update_interval: 30s
